# Generated by Django 2.0.6 on 2018-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('uemail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('umob', models.CharField(max_length=50)),
                ('ugen', models.CharField(max_length=50)),
                ('urole', models.CharField(max_length=50)),
            ],
        ),
    ]
